### ISSUE TITLE
Crash when opening sync settings

### ISSUE THREAD

**Issue by picsel2** [diegogangl/gtg#14]
## Description

Clicking "Synchronization" in the main menu throws an exception.

## Error log

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/GTG/gtk/application.py", line 389, in open_backends_manager
    self.open_edit_backends()
  File "/app/lib/python3.10/site-packages/GTG/gtk/application.py", line 478, in open_edit_backends
    self.backends_dialog = BackendsDialog(self.ds)
  File "/app/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 72, in __init__
    self._create_widgets_for_conf_panel()
  File "/app/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 172, in _create_widgets_for_conf_panel
    self.config_panel = ConfigurePanel(self)
  File "/app/lib/python3.10/site-packages/GTG/gtk/backends/configurepanel.py", line 43, in __init__
    self.req = backends.get_requester()
AttributeError: 'BackendsDialog' object has no attribute 'get_requester'
```

**Software versions:**
* Getting Things GNOME! v0.6-311-gd1441c20
* CPython 3.10.12 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0]
* GTK 4.10.4, GLib 2.76.3
* PyGLib 3.44.1, PyGObject 3.44.1
* Linux-6.4.7-200.fc38.x86_64-x86_64-with-glibc2.35
* Flatpak 1.15.4
* Flatpak runtime: runtime/org.gnome.Platform/x86_64/44 (584d7c3e03c7315975c6711d6503622c0b39c109b6faa89254a87d24cf918c6e)
* Flatpak app: org.gnome.GTGDevel (8d66dfd14a701023afa31bc04398365807554dff3081a4cb7031fc0095ee660a)

## Note

This is a report against the branch from https://github.com/getting-things-gnome/gtg/pull/894

**Comment by diegogangl** [comment]
Fixed but we still need to port the caldav backend
