### ISSUE TITLE
Interacting with new empty task triggers KeyError

### ISSUE THREAD

**Issue by SqAtx** [diegogangl/gtg#21]
I'm on commit 2fa2094d4914df119264711a953593b409c45f8e.

* Create new task using the + in the top-left corner
* Immediately close the new task dialog
  * This results in a task named "New Task", which isn't great, but I think 0.6 does this as well
* Open "New Task" by double-clicking on it

```
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/taskview.py", line 199, in process
    start = self.detect_title()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/taskview.py", line 543, in detect_title
    self.refresh_cb(title)
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 521, in refresh_editor
    self.light_save()
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 829, in light_save
    self.save()
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 805, in save
    t = self.app.ds.tasks.get(self.task.id)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/src/gtg/.local_build/install/lib/python3/dist-packages/GTG/core/tasks.py", line 723, in get
    return self.lookup[tid]
           ~~~~~~~~~~~^^^^^
KeyError: UUID('a7020fb3-c9b0-4734-9d3d-51400135afa6')
```

**Software versions:**
* GTG (debug version) v0.6-331-g2fa2094d
* CPython 3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0]
* GTK 4.10.4, GLib 2.76.0
* PyGLib 3.44.1, PyGObject 3.44.1
* Linux-6.2.0-34-generic-x86_64-with-glibc2.37
```

**Comment by SqAtx** [comment]
It looks like it's because `TaskEditor.destruction()`, which is called when closing the task, removes it from the list of taks:
```
        if self.is_new():
            self.app.ds.tasks.remove(tid)
```
Which makes sense.

Therefore, the problem is that the new task shouldn't be visible in the UI. It doesn't actually exist in the DB. I confirmed that by restarting GTG after creating the new task, and it doesn't appear in the list.

It sounds similar to
> Right-click Deleting a tag from the sidebar doesn't have any visible effect after the confirmation dialog (removal throughout the GUI only happens after app restart)

in https://github.com/getting-things-gnome/gtg/pull/894#issuecomment-1743484451

Not sure if this should be blocking the merge.

**Comment by SqAtx** [comment]
OK so the task gets added to the UI from https://github.com/diegogangl/gtg/blob/2fa2094d4914df119264711a953593b409c45f8e/GTG/core/tasks.py#L901-L902:

```
    def add(self, item: Any, parent_id: UUID = None) -> None:
        """Add a tag to the tagstore."""

        super().add(item, parent_id)

        if not parent_id:
            self.model.append(item)

        # ...
```
`model` being the `ListStore`.

This happens before opening the task editing window:
```
    def on_add_task(self, widget=None):
        new_task = self.app.ds.tasks.new()

        for tag in self.sidebar.selected_tags():
            new_task.add_tag(tag)

        self.app.open_task(new_task)
```
https://github.com/diegogangl/gtg/blob/2fa2094d4914df119264711a953593b409c45f8e/GTG/gtk/browser/main_window.py#L944-L950

So calling `self.app.ds.tasks.new()` both creates the task in the store and adds it to the UI, but `self.app.ds.tasks.remove(tid)` only removes it from the store.
