### ISSUE TITLE
PluginAPI object has no attribute "get_requester" (traceback prevents startup with Python 3.12)

### ISSUE THREAD

**Issue by nekohayo** [diegogangl/gtg#24]
Removing the `.local_build` folder and running this branch on a distro that ships Python 3.12, such as Fedora 39, you get:

```python-traceback
Traceback (most recent call last):
  File "GTG/gtk/application.py", line 151, in do_activate
    self.init_shared()
  File "GTG/gtk/application.py", line 232, in init_shared
    self.init_plugin_engine()
  File "GTG/gtk/application.py", line 258, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "GTG/core/plugins/engine.py", line 206, in activate_plugins
    plugin.instance.activate(api)
  File "GTG/plugins/gamify/gamify.py", line 282, in activate
    self.signal_connect_id = self.plugin_api.get_requester().connect("status-changed",
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PluginAPI' object has no attribute 'get_requester'
```

This might be spread throughout the code. There may also be other similar deprecation-related tracebacks when running with Python 3.12.

**Comment by nekohayo** [comment]
This was fixed by 1069c60d6
